version: "3.8"

services:
  mysql-spring-boot:
    image: mysql
    container_name: mysql-spring-boot
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
