server:
  port: '8765'
eureka:
  instance:
    prefer-ip-address: 'true'
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: '1.0'
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
  application:
    name: api-gateway
springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: api-gateway
        display-name: api-gateway-service
      - url: /portfolio-service/v3/api-docs
        name: portfolio-service
        display-name: portfolio-service
