pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build Docker image') {
            steps {
                sh 'mvn dockerfile:build'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh 'mvn dockerfile:run'
            }
        }
    }
}
