resilience4j:
  circuitbreaker:
    instances:
      currency-conversion-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#  ratelimiter:
#    instances:
#      currency-conversion-rateLimiter:
#        timeout-duration: 0s
#        event-consumer-buffer-size: '50'
#        register-health-indicator: 'true'
#        limit-for-period: '2'
#        subscribe-for-events: 'true'
#        limit-refresh-period: 60s
#        allow-health-indicator-to-fail: 'true'
#    metrics:
#      enabled: 'true'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: health

