INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES (10001,'USD','THB',65,'');
INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES (10002,'EUR','THB',75,'');
INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES (10003,'AUD','THB',25,'');