eureka:
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: 'true'
springdoc:
  swagger-ui:
    path: /portfolio-service/swagger-ui.html
  api-docs:
    path: /portfolio-service/v3/api-docs
spring:
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/portfolio?createDatabaseIfNotExist=true
  sql:
    init:
      mode: always
server:
  port: '8000'
